/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatservidor;

import java.awt.AWTException;
import java.io.IOException;
import java.net.UnknownHostException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class ventanaConexion extends javax.swing.JFrame {

    /**
     * Creates new form ventanaConexion
     */
    
    public static int puerto = 10327;
    public VentanaChat ventanaChat;
    
    public ventanaConexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoPuerto = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldPuerto = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        labelPuertoActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        bEmpezar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bPuerto = new javax.swing.JMenuItem();

        dialogoPuerto.setMinimumSize(new java.awt.Dimension(400, 400));
        dialogoPuerto.setResizable(false);

        jLabel3.setText("Puerto por defecto: 10327");

        jLabel4.setText("Establecer otro puerto:");

        fieldPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPuertoActionPerformed(evt);
            }
        });

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        labelPuertoActual.setText("Puerto actual: 10327");

        javax.swing.GroupLayout dialogoPuertoLayout = new javax.swing.GroupLayout(dialogoPuerto.getContentPane());
        dialogoPuerto.getContentPane().setLayout(dialogoPuertoLayout);
        dialogoPuertoLayout.setHorizontalGroup(
            dialogoPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoPuertoLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(dialogoPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldPuerto)
                    .addComponent(bAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoPuertoLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(dialogoPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoPuertoLayout.createSequentialGroup()
                        .addGroup(dialogoPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(labelPuertoActual))
                        .addGap(125, 125, 125))
                    .addGroup(dialogoPuertoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(117, 117, 117))))
        );
        dialogoPuertoLayout.setVerticalGroup(
            dialogoPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoPuertoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPuertoActual)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(fieldPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bAceptar)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nickname:");

        bEmpezar.setText("Iniciar Sesión");
        bEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpezarActionPerformed(evt);
            }
        });

        jMenu1.setText("Opciones...");

        bPuerto.setText("Puerto...");
        bPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPuertoActionPerformed(evt);
            }
        });
        jMenu1.add(bPuerto);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(bEmpezar)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(bEmpezar)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpezarActionPerformed

        if(ventanaChat == null){
            //JOptionPane option = new JOptionPane("Estableciendo conexión...", JOptionPane.INFORMATION_MESSAGE, JOptionPane.CANCEL_OPTION);
            //JDialog dialogo = option.createDialog(this, "Conectando...");
            //dialogo.setVisible(true);
            ventanaChat = new VentanaChat(puerto, this);
            ventanaChat.setVisible(true);
        }else{
            try{
                ventanaChat.chat.EstablecerConexion(puerto);
            }catch(UnknownHostException e){
            }catch(IOException e){
            }catch(AWTException e){
            }catch(ClassNotFoundException e){}
        }
        ventanaChat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bEmpezarActionPerformed

    private void fieldPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPuertoActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        if(!fieldPuerto.getText().equals("")){
            puerto = Integer.parseInt(fieldPuerto.getText());
            labelPuertoActual.setText("Puerto actual: " + puerto);
            fieldPuerto.setText("");
            try {
                if (ventanaChat != null) {
                    ventanaChat.chat.CerrarConexion();
                }
            } catch (IOException e) {
            }
        }
        dialogoPuerto.setVisible(false);
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPuertoActionPerformed
        dialogoPuerto.setVisible(true);
    }//GEN-LAST:event_bPuertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaConexion().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bEmpezar;
    private javax.swing.JMenuItem bPuerto;
    private javax.swing.JDialog dialogoPuerto;
    private javax.swing.JTextField fieldPuerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelPuertoActual;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
